### ISSUE TITLE
Error when trying to import

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/ZoteroImport#1]
When I try to import a Zotero Group library collection, I get the following error:

There was an error.

exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:281
Stack trace:
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'stream_socket_e...', '/websites/omeka...', 281, Array)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php(281): stream_socket_enable_crypto(Resource id #653, true, 2)
#2 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client.php(1370): Zend\Http\Client\Adapter\Socket->connect('api.zotero.org', 443, true)
#3 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#4 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(140): Zend\Http\Client->send()
#5 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(45): ZoteroImport\Controller\IndexController->sendApiRequest(Array)
#6 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): ZoteroImport\Controller\IndexController->importAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#17 {main}

Next exception 'Zend\Http\Client\Adapter\Exception\RuntimeException' with message 'Unable to enable crypto on TCP connection api.zotero.org' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client/Adapter/Socket.php:308
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client.php(1370): Zend\Http\Client\Adapter\Socket->connect('api.zotero.org', 443, true)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-http/src/Client.php(893): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#2 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(140): Zend\Http\Client->send()
#3 /websites/omekadev/home/www/omeka-s/modules/ZoteroImport/src/Controller/IndexController.php(45): ZoteroImport\Controller\IndexController->sendApiRequest(Array)
#4 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): ZoteroImport\Controller\IndexController->importAction()
#5 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#7 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#15 {main}

**Comment by jimsafley** [comment]
Does this happen every time you attempt an import? Does this happen, say, when importing the entire group library? What group and what collection are you trying to import?

**Comment by mebrett** [comment]
It happened every time I tried to import. I was trying to import https://www.zotero.org/groups/newmedia804/items/collectionKey/FP6XB7WM.

**Comment by mebrett** [comment]
Same error if I try to import from my library with and without an API key, and when trying to import just stuff from a group (no collection)

**Comment by jimsafley** [comment]
It's possible that your server doesn't have OpenSSL installed. If it isn't installed, you (or the systems administrator) could install it. If it is installed, you probably need to change the path to SSL certificate directory. First find where the certificate directory is on your server, open `config/local.config.php`, and add this to the array:

``` php
    'http_client' => [
        'sslcapath' => '/path/to/your/certs',
    ],
```

Replacing `/path/to/your/certs` with the real path to your certificate directory.

**Comment by mebrett** [comment]
I'm doing all of this on the shared install. 
I'll check with Roberto.
