### ISSUE TITLE
Separate "past imports" out into its own subitem in navigation

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/ZoteroImport#11]
All the other importers currently show the "Past Imports" view like so:

<img width="173" alt="screen shot 2016-11-15 at 5 01 48 pm" src="https://cloud.githubusercontent.com/assets/606764/20326082/3d2d53b8-ab55-11e6-8cf1-f43504ded925.png">

In core, we're avoiding tabbed navigation that points to separate views, especially if one tab contains a form so that the user doesn't navigate away from changes by accident.

**Comment by jimsafley** [comment]
We've recently had a discussion about this very thing: https://github.com/omeka-s-modules/ZoteroImport/issues/8

I'm not partial to any solution, so whatever you and the testers decide, I can do.

**Comment by kimisgold** [comment]
Sorry for the repeat issue. I'll continue discussion there.

**Comment by jimsafley** [comment]
@kimisgold  Sorry about re-opening this, but now I see a problem.

If I want to see past imports I have to click the main "Zotero Import" link and then the "Past Imports" sub-link. Not too annoying, except when the "Zotero Import" link is pushed under the fold and I have to scroll twice to get to past imports. I suspect this annoyance will become more common as people install more modules.

One solution that fits an existing pattern is to integrate the import and past import pages into one tabbed view. This would work but both pages have separate forms, one to import and another to undo an import, so a user could get confused.

Another solution is to provide links at the top of the page that are not tabs. What do you think?

**Comment by sheilabrennan** [comment]
This is a good discussion. But for this stage, I agree with @kimisgold's desire to remain consistent across the modules.

One of the strategies you've suggested, @jimsafley, for placing links at the top of the page within each of the applicable modules' might be a good option to consider for another release.
