### ISSUE TITLE
Not all items coming through

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/ZoteroImport#14]
Testing as part of #7 

First import: from https://www.zotero.org/mebrett/items/collectionKey/CPNQM9G2 using API key, importing files, with a datestamp. There are 75 items in the collection, 9 of which are before the datestamp I picked, so I should have gotten 66 items. The import ([job338](http://dev.omeka.org/omeka-s/admin/job/338) brought in 58 items.

I tried running the same import *without* the datestamp qualifier, but everything else the same. That import ([job339](http://dev.omeka.org/omeka-s/admin/job/339)) brought in 67 items. 

I've identified a few of the items which didn't get pulled in, but I don't see their item ids in the error log for either job. [This item](https://www.zotero.org/mebrett/items/collectionKey/CPNQM9G2/itemKey/B5M2IFCU/itemPage/3) is missing from 339, for example.

**Comment by jimsafley** [comment]
The rules for importing an item are the same as creating an item in Omeka. Files that have disallowed media types or file extensions will be rejected. Files that cannot be downloaded for any reason are rejected. Look at your job log. I suspect you'll see messages that account for the missing items.

**Comment by mebrett** [comment]
In 338 (with timestamp) [this item](https://www.zotero.org/mebrett/items/collectionKey/CPNQM9G2/itemKey/998KCVDT/itemPage/2) didn't get pulled in, even though it meets the timestamp requirements I gave it (Jan 1, 2014). But it did come through in 339. I can't find its item key (itemKey/998KCVDT) in the log for 338 at all

**Comment by mebrett** [comment]
I figured out one of the things which was confusing me - the item keys in the error log go straight to the snapshot or file, rather than the parent item (the zotero record).  I'll make a note of that, and of possible file errors, in the documentation.

(still not sure why "His Highness" borked that first time - neither of its files show up in the log)

**Comment by jimsafley** [comment]
I'm working on a way to avoid 404 Not Found errors when downloading files, which should reduce the amount of items the import skips.

**Comment by jimsafley** [comment]
Reinstall the module and try importing your files again.You should see more items during import.

**Comment by mebrett** [comment]
Yes, they all came through. 
And it worked perfectly with "after date" set as well.
