### ISSUE TITLE
please consider a "sideload" option

### ISSUE THREAD

**Issue by persianphilosopher** [omeka-s-modules/ZoteroImport#16]
Been following the development of Omeka-S and have tested it on different servers. It is a wonderful new platform in my mind, especially for Zotero. With Omeka classic, the Zotero import never worked managed to finish an import regardless of how much I tweaked the background processes.

With  Omeka-S, the Zotero import is working much better and your raising the memory to 500M certainly helps, but it still struggles with the  larger of the two collections (20k items) I am trying to build and I concur with @jimsafley and his comment on [issue#12](https://github.com/omeka-s-modules/ZoteroImport/issues/12#issuecomment-261546993) .

Would you please, please consider allowing a "sideload" option, similar to CSV import: it would save so much time if one could upload a "flat file" from the Zotero feed. I hope that on the "Import" pane, there  would be another field so that one could either enter the url/api-key or upload a file in the same format as the feed for the plugin to process.  (It would be even better if it could be a Zotero exported file, but I will take any option).

Right now, the process depends on *two* servers playing nicely with each other. This suggested option would eliminate the quirks of a given Omeka-S server, which hypothetically could not use 500M (though unlikely). It would in general give the admin/dev of the Omeka-S server a bit more flexibility.

**Comment by jimsafley** [comment]
It's an interesting request, but I'm still not sure there's a problem to solve. The module roughly follows Zotero's recommended steps for synchronizing a client with the Zotero server, and we've taken steps beyond the raising the memory limit to fix the memory leaks that used to sink imports. Also, the Zotero API sets a maximum number of results to return with a single request so we'd have to make many requests to compile the exported data anyway.

Would you point me to the Zotero collection that the module is struggling with? 20K items is very large and I'd like to benchmark it.

**Comment by persianphilosopher** [comment]
Thank you @jimsafley for your reply!

First of all: I readily acknowledge that 20k is very large. As I am not the sole owner of this private collection, allow me to ask my fellow scholars.  I hope you understand that my being cautious is only related to the situation and perhaps my username can serve as a hint regarding my peers' need to keep this project within the research group without bringing too much attention to it.

Regarding benchmarks: Over the holidays, I installed Omeka-S on a local computer. Since my desktop has more power than the typical host that we can afford for this project, the hiccups I have experienced with the different webhosts disappeared.  I will try to move the database online and see if it works well. 

In my mind this experience nevertheless confirmed my concern of finding a way to tame the variables, already an issue for the classical site ([with various hosts](http://omeka.org/codex/Hosting_Suggestions)). A flat file sideload, I think, might just reduce the obstacles. 

Having said that: I deeply appreciate the care you all have put into Omeka-S and this plugin. It is worlds apart and ahead of the classical site and plugin. Please feel free to close this topic if my suggestion does not suit the road-map. I have no unreasonable expectations, I assure you. 

If at all possible, I would appreciate your pointing me in the right direction so I can try to play with this on my own: I don't know if there will be a zotero "vocabulary" added in the future but I confess that trying to match field by field the zotero csv export with the csv-plugin proved more complicated than I expected. I hope to have the time to dig into the codes of both this plugin and the cvs one to better match the schema but any hint would be greatly appreciated.

**Comment by jimsafley** [comment]
I respect your need for confidentiality. I would appreciate if you could describe the hiccups you've experienced with the module. Do the import jobs not complete? Each job has a log that may shed light on what's happening.

Omeka S ships with the [BIBO](http://bibliographic-ontology.org/) vocabulary, which is essentially the Zotero vocabulary. [Here](https://github.com/omeka-s-modules/ZoteroImport/tree/master/src/Job) you can see the maps we're using to crosswalk Zotero and Omeka S metadata.

**Comment by persianphilosopher** [comment]
I started fresh again - clean install - to test things with a new and generally solid host (a2hosting). 

I initiated the Zotero import this morning at 9:15am (eastern time). As of now, about seven hours later, it still says "Import starting" with zero item imported (and I did not ask it to import files). 

When I click on it (Job #1), it says [no log]. Should I stop it or let it run until it comes up with a log to share with you?

**Comment by jimsafley** [comment]
I'm certain something went wrong immediately after you initiated the import. A hanging "Starting" status indicates the import never started because there was a fatal error early in the background process. Unfortunately it's near impossible to catch and log a fatal error within the job, but you should be able to see the error in the PHP error log. Ask your host how you can review the log.

At any rate, I suspect that a) the host disables program execution functions, or b) you need to configure the correct `phpcli_path` in /config/local.config.php. Ask your host for this path.

**Comment by persianphilosopher** [comment]
Can't quite figure it out. You are right that it must be host related but it can't be php-cli for two reasons.

1. I had already set the path (/usr/bin/php-cli) 
2. My second attempt - no settings changed but a new import - has had "Import in progress" for the past four hours but nothing actually imported and empty logs.

I downloaded the entire omeka folder from the host and ran it on a clean local server (only changing the database.ini) and it imported 17k references fairly swiftly. 

I certainly don't want to be a distraction. Ultimately, though, it will be what you guys (Omeka) envision. I am sure that the project easily works for a university, with its own servers and sysadmins. But if small research groups such as ours and individual professors (esp those of us in the humanities!) are also expected to benefit from the platform, I think it may be worth finding out what the hiccups are on a shared-host. 

I am more than happy to share any details that could help. I am also happy to hand over my logins if you want to see for yourself. In that case, please feel free to email me (erfani@american.edu). 

Thank you for your time and care.

**Comment by jimsafley** [comment]
The only way to see what's happening is to run the background process yourself. You'll need terminal access to the host server and the ID of a job that's been giving you trouble. Run these commands:

```
$ cd /path/to/omeka-s
$ php application/data/scripts/perform-job.php --job-id <id> --base-path omeka
```

You should see an error output.
