### ISSUE TITLE
Warning about importing files without entering key is almost off-screen

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/ZoteroImport#17]
Tried to import files, and got the flash message that I hadn't entered an API key. However, just off the 'Import Files' checkbox, it looks like there's a message that floated off to the right, just outside the screen. Not horizontal scroll to get to it.
![zoteroimportfilescrollmessage](https://user-images.githubusercontent.com/153262/29721581-c2f7789c-898b-11e7-9c15-4927998ab75c.png)

**Comment by patrickmj** [comment]
All the styles come from core, so will need @kimisgold 's guidance on this

**Comment by kimisgold** [comment]
Commit https://github.com/omeka/omeka-s/commit/619ccb7eec3967d2abb546835534359158ed1d83 should address this wrapping problem. Can you pull and confirm?

**Comment by patrickmj** [comment]
Yep! All good!
