### ISSUE TITLE
"Hang" followed eventually by out of memory error

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-modules/ZoteroImport#5]
Running an import seems to import a lot of items fairly quickly, but then seems to sit and do nothing for minutes, then finally dies:

`
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 616 bytes) in /mnt/storage/htdocs/omeka3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91
`

Neither the Error status nor the memory limit message is logged on the Job.

**Comment by jimsafley** [comment]
@zerocrates Does this still happen?

**Comment by jimsafley** [comment]
Temporarily "fixed" by raising memory limit. Long term solutions here: #12
